combineTest File3 and mergeFile3s created to facilitate recusive File3 merging (lists must be equivalently ordered) mergeFile3s used in load names, hopefully this will work to handle missing names empty names purged from namelist before saving
ERROR: LocalMixDatabase discovered to be broken